### ISSUE TITLE
Short-term goals of this repo

### ISSUE THREAD

**Issue by abhishek47kashyap** [williamshen-nz/rerun-robotics#4]
Rerun is a great visualization tool and I work with robot manipulation so I'm curious if you've decided on any near-term goals for what you intend to do with this repository :)

**Comment by williamshen-nz** [comment]
Hi, thanks for the question! Myself and others in the lab mostly use this package for logging Franka Panda trajectories and as helpers for other robots.

We've used rerun extensively for logging other data like images and point clouds for visualizing datasets, debugging planners, optimizers, etc. However, the logging tends to be pretty specific to each use-case, so I think it may be difficult to write helpers that are generalizable across projects.

I would love to hear any ideas you might have for features to add! :)

**Comment by abhishek47kashyap** [comment]
Thanks for the details, I'm still getting acquainted with Rerun and as yet don't know how much of what I need is already available. If I have any feature suggestions will create a new issue to start the discussion.
